# tasks file for tmux-conf
- name: mkdir repo's parent directory
  file:
    path: "{{tmux_conf_cloned_dest|dirname}}"
    state: directory
- name: Clone the tmux_conf repository
  git:
    repo: "{{tmux_conf_repo}}"
    dest: "{{tmux_conf_cloned_dest}}"
    version: "{{tmux_conf_version}}"
- name: Make symbolic link
  file:
    src: "{{tmux_conf_cloned_dest}}/{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  with_items: "{{tmux_conf_links}}"
